/**
 * @file App/Utils/Inc/pinout.h
 * @authors Jude Merritt
 * @brief Pinout definitions for the flight computer
 */

#pragma once

#include <stdint.h>
#include "stm32f4xx_hal.h"

// LEDs
#define LED_MCU_PORT             GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL LED PORT
#define LED_MCU_PIN              GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL LED PIN
#define LED_APOGEE_PORT          GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL APOGEE LED PORT
#define LED_APOGEE_PIN           GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL APOGEE LED PIN
#define LED_APOGEE_BACKUP_PORT   GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL APOGEE BACKUP LED PORT
#define LED_APOGEE_BACKUP_PIN    GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL APOGEE BACKUP LED PIN
#define LED_MAIN_PORT            GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL MAIN LED PORT
#define LED_MAIN_PIN             GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL MAIN LED PIN
#define LED_MAIN_BACKUP_PORT     GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL MAIN BACKUP LED PORT
#define LED_MAIN_BACKUP_PIN      GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL MAIN BACKUP LED PIN

// Pyro Channels
#define APOGEE_PYRO_PORT        GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL APOGEE PYRO PORT
#define APOGEE_PYRO_PIN         GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL APOGEE PYRO PIN
#define APOGEE_BACKUP_PYRO_PORT GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL APOGEE BACKUP PYRO PORT
#define APOGEE_BACKUP_PYRO_PIN  GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL APOGEE BACKUP PYRO PIN
#define MAIN_PYRO_PORT          GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL MAIN PYRO PORT
#define MAIN_PYRO_PIN           GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL MAIN PYRO PIN
#define MAIN_BACKUP_PYRO_PORT   GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL MAIN BACKUP PYRO PORT
#define MAIN_BACKUP_PYRO_PIN    GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL MAIN BACKUP PYRO PIN

// MS5611 (Barometer)
#define MS5611_CS_PORT   GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL MS5611 CS PORT
#define MS5611_CS_PIN    GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL MS5611 CS PIN
#define MS5611_SCK_PORT  GPIOA
#define MS5611_SCK_PIN   GPIO_PIN_5
#define MS5611_MISO_PORT GPIOA
#define MS5611_MISO_PIN  GPIO_PIN_4
#define MS5611_MOSI_PORT GPIOA
#define MS5611_MOSI_PIN  GPIO_PIN_7

// BMI088 (Accelerometer)
#define ACCEL_CS_PORT   GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL BMI088 CS PORT
#define ACCEL_CS_PIN    GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL BMI088 CS PIN
#define ACCEL_SCK_PORT  GPIOA
#define ACCEL_SCK_PIN   GPIO_PIN_5
#define ACCEL_MISO_PORT GPIOA
#define ACCEL_MISO_PIN  GPIO_PIN_4
#define ACCEL_MOSI_PORT GPIOA
#define ACCEL_MOSI_PIN  GPIO_PIN_7

// BMI088 (Gyroscope)
#define GYRO_CS_PORT   GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL BMI088 CS PORT
#define GYRO_CS_PIN    GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL BMI088 CS PIN
#define GYRO_SCK_PORT  GPIOA
#define GYRO_SCK_PIN   GPIO_PIN_5
#define GYRO_MISO_PORT GPIOA
#define GYRO_MISO_PIN  GPIO_PIN_4
#define GYRO_MOSI_PORT GPIOA
#define GYRO_MOSI_PIN  GPIO_PIN_7

// W25Q128JVPIQ (Flash Memory)
#define EXTERN_FLASH_CS_PORT   GPIOA      // CHANGE ME WHEN YOU HAVE THE ACTUAL BMI088 CS PORT
#define EXTERN_FLASH_CS_PIN    GPIO_PIN_1 // CHANGE ME WHEN YOU HAVE THE ACTUAL BMI088 CS PIN
#define EXTERN_FLASH_SCK_PORT  GPIOB
#define EXTERN_FLASH_SCK_PIN   GPIO_PIN_10
#define EXTERN_FLASH_MISO_PORT GPIOB
#define EXTERN_FLASH_MISO_PIN  GPIO_PIN_14
#define EXTERN_FLASH_MOSI_PORT GPIOB
#define EXTERN_FLASH_MOSI_PIN  GPIO_PIN_15

// PS1240P02BT (Piezo Buzzer)
#define BUZZER_PORT GPIOA
#define BUZZER_PIN  GPIO_PIN_0